### ISSUE TITLE
Queue items don't appear when using a Redis queue

### ISSUE THREAD

**Issue by martijnvanonz** [jalendport/craft-queuemanager#12]
It looks like the queue items don't appear when using the craft Redis queue. Am I missing something? Or is this not supported yet?

**Comment by samatcd** [comment]
I'm having this issue too. In `config/app.php` I've got the following config:

```php
return [
    'components' => [
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => getenv('REDIS_HOST'),
            'port' => getenv('REDIS_PORT') ?: 6379,
            'password' => getenv('REDIS_PASSWORD') ?: null,
            'retries' => 1,
        ],
        'queue' => [
            'class' => \yii\queue\redis\Queue::class,
            'redis' => 'redis', // Redis connection component or its config
            'channel' => 'queue', // Queue channel key
        ],
    ]
];
```

Queue Manager just reports "There are no jobs in the queue.", though I can see logs from my worker which is actively processing jobs.

**Comment by samatcd** [comment]
I see — looking in `services/QueueService.php` shows that this plugin does queries against the database directly, so it's only designed with default database queue in mind.
