### ISSUE TITLE
Craft 4 compatibility?

### ISSUE THREAD

**Issue by patrikalienus** [jalendport/craft-queuemanager#21]
Will this be upgraded to work with Craft 4?

**Comment by maxfenton** [comment]
@jalendport If this is something that's still needed with Craft 4 and you're looking for someone to take over the repo and do the migration to make it work, talk to @engram-design (He did that for another plugin I rely on)

**Comment by engram-design** [comment]
Is there much reason to have this available for Craft 3 - not to mention Craft 4 - with the native Queue utility?

**Comment by jalendport** [comment]
Yeah I don't see a reason to upgrade this to Craft 4 now that there's a native way to view/interact with the queue in the CP.
