### ISSUE TITLE
[FR] Email Notifications

### ISSUE THREAD

**Issue by samhibberd** [jalendport/craft-queuemanager#5]
Really useful plugin, it would be great if you could setup email notifications for failed tasks.

**Comment by lukeyouell** [comment]
@samhibberd I considered this, but depending on how many jobs are being run you could end up with lots of emails being sent out. The solutions I considered are either limiting how many emails are sent out within a certain period of time, or sending some sort of daily summary, but that would require the developer to set up a cron job.

**Comment by samhibberd** [comment]
Could you setup a custom event which triggers on task fail / success that way the developer could hook into that and do anything they want depending on the type of task?

**Comment by lukeyouell** [comment]
@samhibberd unfortunately there's no way to trigger an event after a task has run, as the plugin only views/manages the tasks. Craft still handles this process in the background.

**Comment by samhibberd** [comment]
Would it not be possible to determine any failed task when the plugin loads and issue notifications for failed tasks and flagging those failed task that emails have already been issued for.

**Comment by lukeyouell** [comment]
Possibly, but the logic is flawed as you'd only be notified once somebody has opened the queue manager. For this reason I don't think it's worth working on right now.

**Comment by samhibberd** [comment]
Fair
