### ISSUE TITLE
[FR] Move queue manager to Utilities tab

### ISSUE THREAD

**Issue by BenParizek** [jalendport/craft-queuemanager#8]
Nice plugin! I wish a simple version of this was included with Craft so troubleshooting some queue issues didn't require accessing the db directly. You nicely solve that!

I haven't looked into the architecture of the plugin too closely but one small thing (that is perhaps largely opinionated) that I think it would be nicer is if the Queue Manager appeared as a tab on the Utilities page. It feels too prominent to always be available in the main sidebar as the primary use is for outlier cases where the queue fails.

Docs on Utility Types here:
https://docs.craftcms.com/v3/extend/utility-types.html

**Comment by lukeyouell** [comment]
Hey Ben! I did consider this, I just didn't feel that the templates fit too well in that section - but I've already had a couple of people suggest this so I'll revisit this in the new year!
